### Step 1: Importing Necessary Libraries
In this first step, we are importing the essential tools we need for our data analysis:
* **`pandas`**: Think of this as an Excel spreadsheet for Python. We use it to read data, display tables, and manipulate data easily.
* **`numpy`**: This is used for working with numbers and doing math.
* **`seaborn` and `matplotlib.pyplot`**: These are used for drawing graphs and charts to visualize our data.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

### Step 2: Loading IMDb Ratings Data
Here, we are loading our first dataset from a file named `title.ratings.tsv`.
* A `.tsv` file is similar to a CSV, but the columns are separated by "tabs" instead of commas.
* We use `pd.read_csv()` to open the file and read it into a table called a 'DataFrame' (named `df_ratings`).
* `df_ratings.info()` shows us a quick summary of the data, such as the total number of rows and what type of data is in each column. This helps us ensure the data loaded correctly.

In [2]:
# TSV stands for tab-separated value
#  it is similar to a CSV file and commonly used for tranfering data between spreadsheets and databases when your data is separated by commas and tabs.
# In this, we have text, layers, and records with one line.

# Load IMDb datasets (TSV)
df_ratings = pd.read_csv("title.ratings.tsv", sep="\t", low_memory=False)

print("\nIMDb Ratings Dataset:")
df_ratings.info()

IMDb Ratings Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1543665 entries, 0 to 1543664
Data columns (total 3 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   tconst         1543665 non-null  object
 1   averageRating  1543665 non-null  float64
 2   numVotes       1543665 non-null  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 35.3+ MB

### Step 3: Loading and Cleaning IMDb Basics Data
Now we are loading a second dataset, `title.basics.tsv`, which contains basic details about movies and shows.
* To save computer memory, we are only loading the specific columns we care about (like the title type, name, and release year).
* We are 'cleaning' the data by telling the computer to only keep rows where the type is a `'movie'`.
* We also check that the `startYear` only contains numbers, and then we convert it to an integer (a whole number) so we can do math on it later.

In [3]:
df_basics = pd.read_csv(
    "title.basics.tsv", 
    sep="\t", 
    usecols = ['titleType', 'tconst', 'primaryTitle', 'originalTitle', 'startYear'],
    dtype = {'startYear': 'object'},
    low_memory=False
)

df_basics = df_basics[df_basics['titleType'] == 'movie']
df_basics = df_basics[df_basics['startYear'].str.isnumeric()]
df_basics['startYear'] = df_basics['startYear'].astype(int)

df_basics.head()

,tconst,titleType,primaryTitle,originalTitle,startYear
8,tt0000009,movie,Miss Jerry,Miss Jerry,1894
144,tt0000147,movie,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,1897
498,tt0000502,movie,Bohemios,Bohemios,1905
570,tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,1906
587,tt0000591,movie,The Prodigal Son,L'enfant prodigue,1907

### Step 4: Exploring Data Operations (Joins)
This cell contains a specific task or reminder for you: **"learn and read about joins in sql and python"**. 

**What is being asked here:**
You are being asked to study how to combine separate, distinct tables of data into one unified table. This concept is fundamentally known as a **"Join"**.
* In SQL databases, you use commands like `INNER JOIN`, `LEFT JOIN`, or `OUTER JOIN` to connect tables using a shared ID or column.
* In Python (specifically the `pandas` library we are using), this exact same concept is done using the `pd.merge()` function.

Understanding what a "join" means and the different ways data can be merged is critical before moving on to the next cell, where we actually execute an inner join!

In [4]:
#  learn and read about joins in sql and python

### Step 5: Combining the IMDb Datasets
In this step, we are combining (or 'merging') the two datasets we loaded in Step 2 and Step 3 into a single table.
* We use a function called `pd.merge()` to do an 'inner join'.
* This means the computer will look at both tables, find relationships using the unique ID column named `tconst`, and put matching rows side-by-side into a new DataFrame called `ratings_and_titles`.

In [5]:
ratings_and_titles = pd.merge(df_ratings, df_basics, on='tconst', how='inner')
ratings_and_titles.head()

,tconst,averageRating,numVotes,titleType,primaryTitle,originalTitle,startYear
0,tt0000009,5.4,223,movie,Miss Jerry,Miss Jerry,1894
1,tt0000147,5.3,555,movie,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,1897
2,tt0000502,4.0,22,movie,Bohemios,Bohemios,1905
3,tt0000574,6.0,978,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,1906
4,tt0000591,5.6,31,movie,The Prodigal Son,L'enfant prodigue,1907

### Step 6: Loading Netflix Data
Now we turn our attention to the Netflix dataset.
* We load `netflix_titles.csv` into a DataFrame.
* We clean the data slightly by dropping (removing) any rows that have missing release years using `.dropna()`.
* Finally, we make sure the `release_year` column is treated as a number rather than text.

In [6]:
# Load Netflix dataset (CSV format)
netflix_titles = pd.read_csv("netflix_titles.csv")

# Drop rows with missing release_year
netflix_titles = netflix_titles.dropna(subset=['release_year'])

# Convert release_year to integer type for analysis
netflix_titles['release_year'] = netflix_titles['release_year'].astype(int)

# Preview first 5 rows
netflix_titles.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

### Step 7: Standardizing Movie Titles
Because we eventually want to match Netflix movies with IMDb movies, we need to make sure their names are formatted exactly the same.
* Sometimes "The Matrix" and "the matrix" might be seen as different texts by the computer.
* To fix this, we create new columns (`title_low` and `primaryTitle_low`) where every letter of the movie title is converted to lowercase using `.str.lower()`.
* This guarantees a fair comparison later on.

In [7]:
# Create lowercase versions of titles in both datasets
# This helps avoid mismatches due to capitalization differences
netflix_titles['title_low'] = netflix_titles['title'].str.lower()
ratings_and_titles['primaryTitle_low'] = ratings_and_titles['primaryTitle'].str.lower()

# Preview the updated columns
netflix_titles[['title', 'title_low']].head()
ratings_and_titles[['primaryTitle', 'primaryTitle_low']].head()

                    primaryTitle               primaryTitle_low
0                     Miss Jerry                     miss jerry
1  The Corbett-Fitzsimmons Fight  the corbett-fitzsimmons fight
2                       Bohemios                       bohemios
3    The Story of the Kelly Gang    the story of the kelly gang
4               The Prodigal Son               the prodigal son

### What to do next?
Now that we have successfully loaded, cleaned, and standardized both the Netflix dataset and the IMDb dataset, the goal is to cross-reference them.

**Next Steps to pursue in your project:**
1. **Merge the Datasets:** Combine the `netflix_titles` table with our `ratings_and_titles` table. You can match them using the lowercase title columns (`title_low` and `primaryTitle_low`). Watch out for movies with identical names; you may want to ensure they also share the same release year.
2. **Handle Mismatches & Missing Data:** After the merge, inspect the resulting table. Some Netflix movies might not have an IMDb match. Decide your strategy for these scenarios (e.g., discard them or keep them without a rating).
3. **Perform Exploratory Data Analysis (EDA):** 
   * What are the most common genres on Netflix with an IMDb rating above 8.0?
   * Find the top directors or cast with exceptionally high average ratings.
   * Are more highly-rated movies recent releases or older classics?
4. **Data Visualization:** Use the seaborn (`sb`) and matplotlib (`plt`) tools you imported in Cell 1 to draw clear visualizations. For example, a bar chart of the top 10 rated Netflix movies.

In [8]:
grouped = ratings_and_titles.groupby('primaryTitle_low').apply(
    lambda x: pd.Series({
        'IMDB_numvotes':x['numVotes'].sum(),
        'IMDB_rating' : np.average(x['averageRating'],weights=x['numVotes'])
    })
).reset_index()
grouped['IMDB_rating'] = grouped['IMDB_rating'].round(1)

grouped.head()

C:\Users\singh\AppData\Local\Temp\ipykernel_17884\803888945.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = ratings_and_titles.groupby('primaryTitle_low').apply(

        primaryTitle_low  IMDB_numvotes  IMDB_rating
0  !women art revolution          263.0          6.9
1                      #            7.0          4.0
2       #1 serial killer           77.0          5.5
3             #1915house           22.0          3.4
4                     #5           23.0          4.7

In [9]:
final = pd.merge(
    netflix_titles,
    grouped,
    left_on='title_low',
    right_on='primaryTitle_low',
    how='left'
)

final = final.drop(['title_low','primaryTitle_low'], axis=1)

final.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB_numvotes,IMDB_rating
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",7426.0,7.4
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,NaN,NaN

In [10]:
final_clean = final[[
    'show_id','type','title','director','cast','country',
    'date_added','release_year','rating','duration','listed_in',
    'IMDB_rating','IMDB_numvotes'
]]

final_clean = final_clean.drop_duplicates()

final_clean['IMDB_rating'] = final_clean['IMDB_rating'].fillna(0)
final_clean['IMDB_numvotes'] = final_clean['IMDB_numvotes'].fillna(0)

final_clean['IMDB_numvotes'] = final_clean['IMDB_numvotes'].astype(int)

final_clean.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,IMDB_rating,IMDB_numvotes
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,7.4,7426
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",0.0,0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",0.0,0
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV",0.0,0
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",0.0,0

In [11]:
final_clean.to_csv("netflix_powerbi.csv", index=False)